// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://binqklkbdlqxlwlumabi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpbnFrbGtiZGxxeGx3bHVtYWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MTE0MjQsImV4cCI6MjA3Njk4NzQyNH0.zIVNMSEibo4FE8Dz4iOuEieKi0ytzDL9EMXu62aA4EY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});